# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 957e70253d032a9b40ec7a5f16e1c090f6473ffea2bf6dfc9d5662ac49f9c9bebf3c0cb659120e94ccf10dcfe84e82bcce176ca3e2926b68d184ed9d228ba4a8

test:
  secret_key_base: 3a46ffaeacb58a8a9b4e50b445c729d07ef3a9d832ec3f79011c3a96908071c9737a576aa3798fb9324c0d2297baf3289125624b0a86174d225826d3abb3d51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
